#Requires -Version 5.1

<#
.SYNOPSIS
    Compares the client access and transport configuration of two Exchange servers and reports every difference.

.DESCRIPTION
    Read only. Use it after Copy-ExchangeServerConfig.ps1 or after running the script generated by
    Export-ExchangeServerConfigScript.ps1 to prove that the new server matches the source, and later as a drift
    check between the members of the DAG.

    The script reads the same objects on both servers and compares every parameter the matching Set cmdlet
    accepts, so the comparison covers exactly what the two other scripts can set. Each compared property becomes
    a row with a status:

      Equal        same value on both servers (only shown with -ShowEqual)
      Different    both have a value and they differ
      SourceOnly   object or value exists on the source only
      TargetOnly   object or value exists on the target only
      Info         a note that needs no action

    Areas: Certificates, ExchangeServer, ClientAccess, VirtualDirectories, OutlookAnywhere, Transport, PopImap
    (settings plus service startup types), MailboxServer, Malware, EventLogLevels, SettingOverrides,
    ReceiveConnectors (settings plus explicit AD permissions), SendConnectors, TransportAgents, ConfigFiles (hash
    of the commonly customised files over the admin share), Iis (Default Web Site root redirect, SSL flags and
    bindings) and Hybrid.

    Before comparing, the source server name and FQDN inside a value are replaced by those of the target, so
    "Default Frontend EX01" equals "Default Frontend EX02" and the Fqdn of a default connector does not show up as
    a difference. Bindings on a specific IP address are translated with -IpAddressMap. Log and queue paths are
    excluded unless -IncludePaths is given.

    Output: a summary per area and the differences on the console, compare.csv with every row and compare.html
    with a coloured table in the output folder. The script exits with code 0 when no differences were found and
    with the number of differences otherwise, so it can gate a change window.

.PARAMETER SourceServer
    Reference server.

.PARAMETER TargetServer
    Server to compare against the reference.

.PARAMETER Area
    Areas to compare. Defaults to all.

.PARAMETER SkipArea
    Areas to leave out.

.PARAMETER OutputPath
    Folder for compare.csv and compare.html. Defaults to a timestamped folder in the current directory.

.PARAMETER ShowEqual
    Also report properties that are equal, for a full side by side documentation of both servers.

.PARAMETER IpAddressMap
    Hashtable that maps source IP addresses to target IP addresses for connector and protocol bindings.

.PARAMETER IncludePaths
    Also compare log, queue and pickup directory paths.

.PARAMETER NoServerNameSubstitution
    Compare values literally without replacing the source server name by the target server name.

.PARAMETER PassThru
    Also return the result rows as objects on the pipeline.

.EXAMPLE
    .\Compare-ExchangeServerConfig.ps1 -SourceServer EX01 -TargetServer EX02

    Shows the differences and writes compare.csv and compare.html.

.EXAMPLE
    .\Compare-ExchangeServerConfig.ps1 -SourceServer EX01 -TargetServer EX02 -ShowEqual -OutputPath C:\Docs\EX02-asbuilt

    Full side by side documentation of both servers.

.EXAMPLE
    .\Compare-ExchangeServerConfig.ps1 -SourceServer EX01 -TargetServer EX02 -Area ReceiveConnectors, SendConnectors -IpAddressMap @{ '10.0.0.11' = '10.0.0.12' }

    Only the mail flow configuration, with the relay binding translated.

.EXAMPLE
    $rows = .\Compare-ExchangeServerConfig.ps1 -SourceServer EX01 -TargetServer EX02 -PassThru
    $rows | Where-Object Status -ne 'Equal' | Out-GridView

.NOTES
    jentech consulting
    Requirements: Exchange Management Shell with View-Only Organization Management, admin share and WinRM access
    to both servers for the ConfigFiles, PopImap service and Iis areas. Windows PowerShell 5.1.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateNotNullOrEmpty()]
    [string] $SourceServer,

    [Parameter(Mandatory = $true, Position = 1)]
    [ValidateNotNullOrEmpty()]
    [string] $TargetServer,

    [ValidateSet('Certificates', 'ExchangeServer', 'ClientAccess', 'VirtualDirectories', 'OutlookAnywhere', 'Transport',
                 'PopImap', 'MailboxServer', 'Malware', 'EventLogLevels', 'SettingOverrides', 'ReceiveConnectors',
                 'SendConnectors', 'TransportAgents', 'ConfigFiles', 'Iis', 'Hybrid')]
    [string[]] $Area,

    [ValidateSet('Certificates', 'ExchangeServer', 'ClientAccess', 'VirtualDirectories', 'OutlookAnywhere', 'Transport',
                 'PopImap', 'MailboxServer', 'Malware', 'EventLogLevels', 'SettingOverrides', 'ReceiveConnectors',
                 'SendConnectors', 'TransportAgents', 'ConfigFiles', 'Iis', 'Hybrid')]
    [string[]] $SkipArea = @(),

    [string] $OutputPath,

    [switch] $ShowEqual,

    [hashtable] $IpAddressMap = @{},

    [switch] $IncludePaths,

    [switch] $NoServerNameSubstitution,

    [switch] $PassThru
)

$script:AllAreas = @('Certificates', 'ExchangeServer', 'ClientAccess', 'VirtualDirectories', 'OutlookAnywhere',
                     'Transport', 'PopImap', 'MailboxServer', 'Malware', 'EventLogLevels', 'SettingOverrides',
                     'ReceiveConnectors', 'SendConnectors', 'TransportAgents', 'ConfigFiles', 'Iis', 'Hybrid')

$script:NeverCopy = @('Identity', 'Server', 'DomainController', 'Force', 'Confirm', 'WhatIf', 'AsJob', 'Name')
$script:PathExclusions = @('*Path', '*Location', '*Directory')
if ($IncludePaths) { $script:PathExclusions = @() }

$script:Results = New-Object System.Collections.Generic.List[object]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Format-ReportValue {
    param($Value)
    if ($null -eq $Value) { return '' }
    if ($Value -is [array]) { return (($Value | ForEach-Object { [string]$_ }) -join '; ') }
    return [string]$Value
}

function Add-Result {
    param(
        [string] $Area,
        [string] $Object,
        [string] $Property,
        $SourceValue,
        $TargetValue,
        [ValidateSet('Equal', 'Different', 'SourceOnly', 'TargetOnly', 'Info')]
        [string] $Status,
        [string] $Message = ''
    )
    if ($Status -eq 'Equal' -and -not $ShowEqual) { return }
    $script:Results.Add([pscustomobject]@{
        Area     = $Area
        Object   = $Object
        Property = $Property
        Source   = Format-ReportValue $SourceValue
        Target   = Format-ReportValue $TargetValue
        Status   = $Status
        Message  = $Message
    })
}

function Convert-ServerName {
    # Source FQDN and NetBIOS name inside a value become the target names, so server specific defaults compare
    # equal. Bounded so that EX01 never matches inside EX010.
    param($Value)
    if ($NoServerNameSubstitution -or $null -eq $Value) { return $Value }
    if ($Value -is [string]) {
        $result = $Value
        if ($script:SourceFqdn -and $script:TargetFqdn) {
            $result = [regex]::Replace($result, [regex]::Escape($script:SourceFqdn), $script:TargetFqdn, 'IgnoreCase')
        }
        $pattern = '(?<![\w-])' + [regex]::Escape($script:SourceShort) + '(?![\w-])'
        return [regex]::Replace($result, $pattern, $script:TargetShort, 'IgnoreCase')
    }
    if ($Value -is [array]) {
        $converted = @(foreach ($item in $Value) { Convert-ServerName -Value $item })
        return ,[string[]]$converted
    }
    return $Value
}

function ConvertFrom-DisplayString {
    param([string] $Text)
    if ($Text -match '^\s*unlimited\s*$') { return 'Unlimited' }
    if ($Text -match '\(([\d,\.\s]+)\s*bytes\)') { return ('{0}B' -f ($Matches[1] -replace '[^\d]', '')) }
    if ($Text -eq '') { return $null }
    return $Text
}

function ConvertTo-SettableValue {
    # Same normalisation as the copy and export scripts: scalars stay, collections become string arrays, sizes
    # become byte counts, empty becomes $null. Comparing normalised values avoids false differences.
    param($Value)
    if ($null -eq $Value) { return $null }
    if ($Value -is [bool] -or $Value -is [int] -or $Value -is [long] -or $Value -is [double] -or $Value -is [decimal]) {
        return $Value
    }
    if ($Value -is [string]) { return (ConvertFrom-DisplayString -Text $Value) }
    if ($Value -is [System.Collections.IEnumerable]) {
        $items = @(foreach ($item in $Value) {
            $converted = ConvertTo-SettableValue -Value $item
            if ($null -ne $converted -and "$converted" -ne '') { [string]$converted }
        })
        if ($items.Count -eq 0) { return $null }
        return ,[string[]]$items
    }
    $memberNames = @($Value.PSObject.Properties | Select-Object -ExpandProperty Name)
    if ($memberNames -contains 'IsUnlimited') {
        if ($Value.IsUnlimited) { return 'Unlimited' }
        return (ConvertTo-SettableValue -Value $Value.Value)
    }
    if (@($Value.PSObject.Methods | Select-Object -ExpandProperty Name) -contains 'ToBytes') {
        return ('{0}B' -f $Value.ToBytes())
    }
    return (ConvertFrom-DisplayString -Text $Value.ToString())
}

function Get-ValueList {
    # Flat array, whatever ConvertTo-SettableValue returned.
    param($Value)
    if ($null -eq $Value) { return ,@() }
    $flat = @()
    foreach ($item in @($Value)) { $flat += $item }
    return ,$flat
}

function Get-CompareKey {
    param($Value)
    if ($null -eq $Value) { return '' }
    if ($Value -is [array]) {
        return ((@($Value | ForEach-Object { ([string]$_).Trim() }) | Sort-Object) -join '|').ToLowerInvariant()
    }
    return ([string]$Value).Trim().ToLowerInvariant()
}

function ConvertTo-PermissionGroupString {
    param($Value)
    if ($null -eq $Value) { return $null }
    $groups = @(("$Value" -split ',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -and $_ -ne 'Custom' })
    if ($groups.Count -eq 0) { return 'None' }
    return ($groups -join ', ')
}

function Convert-Binding {
    # Source bindings with a mapped address are rewritten so an intentional address difference is not reported.
    param($Binding)
    if ($null -eq $Binding) { return $null }
    $result = @()
    foreach ($entry in @($Binding)) {
        if ($entry -match '^\[(.+)\]:(\d+)$' -or $entry -match '^(.+):(\d+)$') {
            $ip = $Matches[1]; $port = $Matches[2]
            if ($IpAddressMap.ContainsKey($ip)) {
                $newIp = [string]$IpAddressMap[$ip]
                if ($newIp -match ':') { $result += ('[{0}]:{1}' -f $newIp, $port) } else { $result += ('{0}:{1}' -f $newIp, $port) }
                continue
            }
        }
        $result += [string]$entry
    }
    return ,[string[]]$result
}

function Get-SettableParameterNames {
    param([string] $CmdletName, [string[]] $Exclude = @())
    $command = Get-Command -Name $CmdletName -ErrorAction Stop
    $common = @([System.Management.Automation.PSCmdlet]::CommonParameters) +
              @([System.Management.Automation.PSCmdlet]::OptionalCommonParameters)
    $names = @()
    foreach ($parameterName in $command.Parameters.Keys) {
        if ($common -contains $parameterName -or $script:NeverCopy -contains $parameterName) { continue }
        $excluded = $false
        foreach ($pattern in $Exclude) {
            if ($parameterName -like $pattern) { $excluded = $true; break }
        }
        if (-not $excluded) { $names += $parameterName }
    }
    return ($names | Sort-Object)
}

function Compare-ObjectSettings {
    # Compares every settable property of two objects and records a row per property.
    param(
        [string] $Area,
        [string] $Object,
        $SourceObject,
        $TargetObject,
        [string] $SetCmdlet,
        [string[]] $Exclude = @(),
        [string[]] $BindingProperties = @()
    )
    if ($SourceObject -is [array]) { $SourceObject = $SourceObject[0] }
    if ($TargetObject -is [array]) { $TargetObject = $TargetObject[0] }
    $parameterNames = Get-SettableParameterNames -CmdletName $SetCmdlet -Exclude $Exclude
    $propertyNames = @($SourceObject.PSObject.Properties | Select-Object -ExpandProperty Name)
    $differences = 0
    foreach ($name in $parameterNames) {
        if ($propertyNames -notcontains $name) { continue }
        $sourceValue = Convert-ServerName -Value (ConvertTo-SettableValue -Value $SourceObject.$name)
        $targetValue = ConvertTo-SettableValue -Value $TargetObject.$name
        if ($name -eq 'PermissionGroups') {
            $sourceValue = ConvertTo-PermissionGroupString -Value $sourceValue
            $targetValue = ConvertTo-PermissionGroupString -Value $targetValue
        }
        if ($BindingProperties -contains $name) { $sourceValue = Convert-Binding -Binding $sourceValue }

        $sourceKey = Get-CompareKey $sourceValue
        $targetKey = Get-CompareKey $targetValue
        if ($sourceKey -eq $targetKey) { $status = 'Equal' }
        elseif ($sourceKey -eq '') { $status = 'TargetOnly' }
        elseif ($targetKey -eq '') { $status = 'SourceOnly' }
        else { $status = 'Different' }
        if ($status -ne 'Equal') { $differences++ }
        Add-Result -Area $Area -Object $Object -Property $name -SourceValue $sourceValue -TargetValue $targetValue -Status $status
    }
    return $differences
}

function Get-TargetCounterpart {
    param($SourceObject, [array] $TargetObjects)
    $wantedName = Convert-ServerName -Value ([string]$SourceObject.Name)
    foreach ($candidate in $TargetObjects) {
        if ([string]$candidate.Name -eq $wantedName) { return $candidate }
    }
    return $null
}

function Write-AreaHeader {
    param([string] $Title)
    Write-Host ''
    Write-Host ('=== {0} ===' -f $Title) -ForegroundColor Cyan
}

# ---------------------------------------------------------------------------
# Areas
# ---------------------------------------------------------------------------

function Invoke-AreaCertificates {
    $areaName = 'Certificates'
    $sourceCerts = @(Get-ExchangeCertificate -Server $script:SourceShort -ErrorAction Stop)
    $targetCerts = @(Get-ExchangeCertificate -Server $script:TargetShort -ErrorAction Stop)
    $authThumbprints = @()
    try { $authConfig = Get-AuthConfig -ErrorAction Stop; $authThumbprints = @($authConfig.CurrentCertificateThumbprint, $authConfig.NextCertificateThumbprint) | Where-Object { $_ } } catch { }

    foreach ($cert in $sourceCerts) {
        $thumbprint = [string]$cert.Thumbprint
        $label = '{0} ({1})' -f $thumbprint, $cert.Subject
        if ([bool]$cert.IsSelfSigned -and $authThumbprints -notcontains $thumbprint) {
            Add-Result -Area $areaName -Object $label -Property 'Certificate' -SourceValue 'self signed' -Status Info -Message 'Server specific, not compared.'
            continue
        }
        $counterpart = $targetCerts | Where-Object { [string]$_.Thumbprint -eq $thumbprint } | Select-Object -First 1
        if ($null -eq $counterpart) {
            Add-Result -Area $areaName -Object $label -Property 'Certificate' -SourceValue $cert.Services -Status SourceOnly -Message 'Certificate missing on the target.'
            continue
        }
        $sourceServices = @(("$($cert.Services)" -split ',') | ForEach-Object { $_.Trim() } | Where-Object { @('IIS', 'SMTP', 'IMAP', 'POP') -contains $_ })
        $targetServices = @(("$($counterpart.Services)" -split ',') | ForEach-Object { $_.Trim() } | Where-Object { @('IIS', 'SMTP', 'IMAP', 'POP') -contains $_ })
        $status = if ((Get-CompareKey $sourceServices) -eq (Get-CompareKey $targetServices)) { 'Equal' } else { 'Different' }
        Add-Result -Area $areaName -Object $label -Property 'Services' -SourceValue $sourceServices -TargetValue $targetServices -Status $status
    }
    foreach ($cert in $targetCerts) {
        if ([bool]$cert.IsSelfSigned) { continue }
        if ($sourceCerts | Where-Object { [string]$_.Thumbprint -eq [string]$cert.Thumbprint }) { continue }
        Add-Result -Area $areaName -Object ('{0} ({1})' -f $cert.Thumbprint, $cert.Subject) -Property 'Certificate' -TargetValue $cert.Services -Status TargetOnly
    }
}

function Invoke-AreaExchangeServer {
    $source = Get-ExchangeServer -Identity $script:SourceShort -ErrorAction Stop
    $target = Get-ExchangeServer -Identity $script:TargetShort -ErrorAction Stop
    Compare-ObjectSettings -Area 'ExchangeServer' -Object 'ExchangeServer' -SourceObject $source -TargetObject $target -SetCmdlet 'Set-ExchangeServer' -Exclude @('ProductKey', 'Static*') | Out-Null
    $status = if ([string]$source.Edition -eq [string]$target.Edition -and [bool]$source.IsExchangeTrialEdition -eq [bool]$target.IsExchangeTrialEdition) { 'Equal' } else { 'Different' }
    Add-Result -Area 'ExchangeServer' -Object 'ExchangeServer' -Property 'Edition' -SourceValue ('{0} (trial: {1})' -f $source.Edition, $source.IsExchangeTrialEdition) -TargetValue ('{0} (trial: {1})' -f $target.Edition, $target.IsExchangeTrialEdition) -Status $status
    $status = if ([string]$source.AdminDisplayVersion -eq [string]$target.AdminDisplayVersion) { 'Equal' } else { 'Different' }
    Add-Result -Area 'ExchangeServer' -Object 'ExchangeServer' -Property 'AdminDisplayVersion' -SourceValue $source.AdminDisplayVersion -TargetValue $target.AdminDisplayVersion -Status $status
}

function Invoke-AreaClientAccess {
    $source = Get-ClientAccessService -Identity $script:SourceShort -IncludeAlternateServiceAccountCredentialStatus -ErrorAction Stop
    $target = Get-ClientAccessService -Identity $script:TargetShort -IncludeAlternateServiceAccountCredentialStatus -ErrorAction Stop
    Compare-ObjectSettings -Area 'ClientAccess' -Object 'ClientAccessService' -SourceObject $source -TargetObject $target -SetCmdlet 'Set-ClientAccessService' `
        -Exclude @('AlternateServiceAccountCredential', 'RemoveAlternateServiceAccountCredentials', 'CleanUpInvalidAlternateServiceAccountCredentials', 'Array') | Out-Null
    $sourceAsa = $false; $targetAsa = $false
    if ($null -ne $source.AlternateServiceAccountConfiguration -and $null -ne $source.AlternateServiceAccountConfiguration.EffectiveCredentials) { $sourceAsa = (@($source.AlternateServiceAccountConfiguration.EffectiveCredentials).Count -gt 0) }
    if ($null -ne $target.AlternateServiceAccountConfiguration -and $null -ne $target.AlternateServiceAccountConfiguration.EffectiveCredentials) { $targetAsa = (@($target.AlternateServiceAccountConfiguration.EffectiveCredentials).Count -gt 0) }
    $status = if ($sourceAsa -eq $targetAsa) { 'Equal' } elseif ($sourceAsa) { 'SourceOnly' } else { 'TargetOnly' }
    Add-Result -Area 'ClientAccess' -Object 'ClientAccessService' -Property 'AlternateServiceAccount' -SourceValue $(if ($sourceAsa) { 'configured' } else { 'none' }) -TargetValue $(if ($targetAsa) { 'configured' } else { 'none' }) -Status $status
}

function Invoke-AreaMailboxServer {
    $source = Get-MailboxServer -Identity $script:SourceShort -ErrorAction Stop
    $target = Get-MailboxServer -Identity $script:TargetShort -ErrorAction Stop
    Compare-ObjectSettings -Area 'MailboxServer' -Object 'MailboxServer' -SourceObject $source -TargetObject $target -SetCmdlet 'Set-MailboxServer' `
        -Exclude ($script:PathExclusions + @('DatabaseCopyActivationDisabledAndMoveNow', 'WorkloadManagementPolicy')) | Out-Null
}

function Invoke-AreaMalware {
    $source = Get-MalwareFilteringServer -Identity $script:SourceShort -ErrorAction Stop
    $target = Get-MalwareFilteringServer -Identity $script:TargetShort -ErrorAction Stop
    Compare-ObjectSettings -Area 'Malware' -Object 'MalwareFilteringServer' -SourceObject $source -TargetObject $target -SetCmdlet 'Set-MalwareFilteringServer' -Exclude @('ForceRescan') | Out-Null
}

function Invoke-AreaVirtualDirectories {
    $areaName = 'VirtualDirectories'
    $directoryTypes = @(
        @{ Get = 'Get-OwaVirtualDirectory';          Set = 'Set-OwaVirtualDirectory';          Exclude = @() },
        @{ Get = 'Get-EcpVirtualDirectory';          Set = 'Set-EcpVirtualDirectory';          Exclude = @() },
        @{ Get = 'Get-WebServicesVirtualDirectory';  Set = 'Set-WebServicesVirtualDirectory';  Exclude = @() },
        @{ Get = 'Get-ActiveSyncVirtualDirectory';   Set = 'Set-ActiveSyncVirtualDirectory';   Exclude = @('ActiveSyncServer') },
        @{ Get = 'Get-OabVirtualDirectory';          Set = 'Set-OabVirtualDirectory';          Exclude = @() },
        @{ Get = 'Get-MapiVirtualDirectory';         Set = 'Set-MapiVirtualDirectory';         Exclude = @() },
        @{ Get = 'Get-PowerShellVirtualDirectory';   Set = 'Set-PowerShellVirtualDirectory';   Exclude = @() },
        @{ Get = 'Get-AutodiscoverVirtualDirectory'; Set = 'Set-AutodiscoverVirtualDirectory'; Exclude = @() }
    )
    foreach ($type in $directoryTypes) {
        try {
            $sourceDirectories = @(& $type.Get -Server $script:SourceShort -ErrorAction Stop)
            $targetDirectories = @(& $type.Get -Server $script:TargetShort -ErrorAction Stop)
        }
        catch { Add-Result -Area $areaName -Object $type.Get -Property '(read)' -Status Info -Message $_.Exception.Message; continue }
        foreach ($directory in $sourceDirectories) {
            $counterpart = Get-TargetCounterpart -SourceObject $directory -TargetObjects $targetDirectories
            if ($null -eq $counterpart) { Add-Result -Area $areaName -Object ([string]$directory.Name) -Property '(exists)' -SourceValue 'present' -Status SourceOnly; continue }
            Compare-ObjectSettings -Area $areaName -Object ([string]$directory.Name) -SourceObject $directory -TargetObject $counterpart -SetCmdlet $type.Set -Exclude $type.Exclude | Out-Null
        }
    }
}

function Invoke-AreaOutlookAnywhere {
    $sourceItems = @(Get-OutlookAnywhere -Server $script:SourceShort -ErrorAction Stop)
    $targetItems = @(Get-OutlookAnywhere -Server $script:TargetShort -ErrorAction Stop)
    foreach ($item in $sourceItems) {
        $counterpart = Get-TargetCounterpart -SourceObject $item -TargetObjects $targetItems
        if ($null -eq $counterpart) { Add-Result -Area 'OutlookAnywhere' -Object ([string]$item.Name) -Property '(exists)' -SourceValue 'present' -Status SourceOnly; continue }
        Compare-ObjectSettings -Area 'OutlookAnywhere' -Object ([string]$item.Name) -SourceObject $item -TargetObject $counterpart -SetCmdlet 'Set-OutlookAnywhere' `
            -Exclude @('ClientAuthenticationMethod', 'DefaultAuthenticationMethod') | Out-Null
    }
}

function Invoke-AreaTransport {
    foreach ($pair in @(
        @{ Get = 'Get-TransportService';         Set = 'Set-TransportService';         Label = 'TransportService' },
        @{ Get = 'Get-FrontendTransportService'; Set = 'Set-FrontendTransportService'; Label = 'FrontendTransportService' },
        @{ Get = 'Get-MailboxTransportService';  Set = 'Set-MailboxTransportService';  Label = 'MailboxTransportService' })) {
        $source = & $pair.Get -Identity $script:SourceShort -ErrorAction Stop
        $target = & $pair.Get -Identity $script:TargetShort -ErrorAction Stop
        Compare-ObjectSettings -Area 'Transport' -Object $pair.Label -SourceObject $source -TargetObject $target -SetCmdlet $pair.Set `
            -Exclude ($script:PathExclusions + @('InternalDNSAdapterGuid', 'ExternalDNSAdapterGuid')) | Out-Null
    }
}

function Invoke-AreaPopImap {
    $areaName = 'PopImap'
    foreach ($protocol in @(
        @{ Get = 'Get-ImapSettings'; Set = 'Set-ImapSettings'; Label = 'ImapSettings'; Services = @('MSExchangeIMAP4', 'MSExchangeIMAP4BE') },
        @{ Get = 'Get-PopSettings';  Set = 'Set-PopSettings';  Label = 'PopSettings';  Services = @('MSExchangePOP3', 'MSExchangePOP3BE') })) {
        $source = & $protocol.Get -Server $script:SourceShort -ErrorAction Stop
        $target = & $protocol.Get -Server $script:TargetShort -ErrorAction Stop
        Compare-ObjectSettings -Area $areaName -Object $protocol.Label -SourceObject $source -TargetObject $target -SetCmdlet $protocol.Set `
            -Exclude $script:PathExclusions -BindingProperties @('SSLBindings', 'UnencryptedOrTLSBindings') | Out-Null
        foreach ($serviceName in $protocol.Services) {
            try {
                $sourceService = Get-CimInstance -ClassName Win32_Service -ComputerName $script:SourceFqdn -Filter ("Name='{0}'" -f $serviceName) -ErrorAction Stop
                $targetService = Get-CimInstance -ClassName Win32_Service -ComputerName $script:TargetFqdn -Filter ("Name='{0}'" -f $serviceName) -ErrorAction Stop
                $status = if ([string]$sourceService.StartMode -eq [string]$targetService.StartMode) { 'Equal' } else { 'Different' }
                Add-Result -Area $areaName -Object $serviceName -Property 'StartMode' -SourceValue $sourceService.StartMode -TargetValue $targetService.StartMode -Status $status
                $status = if ([string]$sourceService.State -eq [string]$targetService.State) { 'Equal' } else { 'Different' }
                Add-Result -Area $areaName -Object $serviceName -Property 'State' -SourceValue $sourceService.State -TargetValue $targetService.State -Status $status
            }
            catch { Add-Result -Area $areaName -Object $serviceName -Property 'StartMode' -Status Info -Message ('Service state not readable remotely: {0}' -f $_.Exception.Message) }
        }
    }
}

function Get-EventLogCategory {
    param([string] $Identity)
    $parts = $Identity -split '\\'
    if ($parts.Count -ge 3) { return (($parts | Select-Object -Skip 1) -join '\') }
    return $Identity
}

function Invoke-AreaEventLogLevels {
    $areaName = 'EventLogLevels'
    $sourceLevels = @{}
    foreach ($level in @(Get-EventLogLevel -Server $script:SourceShort -ErrorAction Stop)) { $sourceLevels[(Get-EventLogCategory -Identity ([string]$level.Identity))] = [string]$level.EventLevel }
    $targetLevels = @{}
    foreach ($level in @(Get-EventLogLevel -Server $script:TargetShort -ErrorAction Stop)) { $targetLevels[(Get-EventLogCategory -Identity ([string]$level.Identity))] = [string]$level.EventLevel }
    foreach ($category in ($sourceLevels.Keys | Sort-Object)) {
        $sourceValue = $sourceLevels[$category]
        $targetValue = $targetLevels[$category]
        if ($sourceValue -eq 'Lowest' -and ($null -eq $targetValue -or $targetValue -eq 'Lowest')) { continue }
        $status = if ($sourceValue -eq $targetValue) { 'Equal' } elseif ($null -eq $targetValue) { 'SourceOnly' } else { 'Different' }
        Add-Result -Area $areaName -Object $category -Property 'EventLevel' -SourceValue $sourceValue -TargetValue $targetValue -Status $status
    }
    foreach ($category in ($targetLevels.Keys | Sort-Object)) {
        if ($sourceLevels.ContainsKey($category) -or $targetLevels[$category] -eq 'Lowest') { continue }
        Add-Result -Area $areaName -Object $category -Property 'EventLevel' -TargetValue $targetLevels[$category] -Status TargetOnly
    }
}

function Invoke-AreaSettingOverrides {
    foreach ($override in @(Get-SettingOverride -ErrorAction Stop)) {
        $servers = Get-ValueList -Value (ConvertTo-SettableValue -Value $override.Server)
        if ($servers.Count -eq 0) { continue }
        $onSource = $servers -contains $script:SourceShort
        $onTarget = $servers -contains $script:TargetShort
        if (-not $onSource -and -not $onTarget) { continue }
        $status = if ($onSource -and $onTarget) { 'Equal' } elseif ($onSource) { 'SourceOnly' } else { 'TargetOnly' }
        Add-Result -Area 'SettingOverrides' -Object ([string]$override.Name) -Property 'Server' -SourceValue $(if ($onSource) { 'scoped' } else { '' }) -TargetValue $(if ($onTarget) { 'scoped' } else { '' }) -Status $status `
            -Message ((ConvertTo-SettableValue -Value $override.Parameters) -join '; ')
    }
}

function Get-AceKey {
    param($Ace)
    $user = Convert-ServerName -Value ([string]$Ace.User)
    return ('{0}|{1}|{2}|{3}' -f $user.ToLowerInvariant(), (Get-CompareKey (ConvertTo-SettableValue -Value $Ace.ExtendedRights)), (Get-CompareKey (ConvertTo-SettableValue -Value $Ace.AccessRights)), [bool]$Ace.Deny)
}

function Get-AceDescription {
    param($Ace)
    $rights = @(Get-ValueList -Value (ConvertTo-SettableValue -Value $Ace.ExtendedRights)) + @(Get-ValueList -Value (ConvertTo-SettableValue -Value $Ace.AccessRights))
    return ('{0}: {1}{2}' -f (Convert-ServerName -Value ([string]$Ace.User)), (($rights | Where-Object { $_ -and $_ -ne 'ExtendedRight' }) -join ','), $(if ([bool]$Ace.Deny) { ' (Deny)' } else { '' }))
}

function Invoke-AreaReceiveConnectors {
    $areaName = 'ReceiveConnectors'
    $sourceConnectors = @(Get-ReceiveConnector -Server $script:SourceShort -ErrorAction Stop)
    $targetConnectors = @(Get-ReceiveConnector -Server $script:TargetShort -ErrorAction Stop)
    foreach ($connector in $sourceConnectors) {
        $label = Convert-ServerName -Value ([string]$connector.Name)
        $counterpart = Get-TargetCounterpart -SourceObject $connector -TargetObjects $targetConnectors
        if ($null -eq $counterpart) {
            Add-Result -Area $areaName -Object $label -Property '(exists)' -SourceValue 'present' -Status SourceOnly -Message 'Connector missing on the target.'
            continue
        }
        Compare-ObjectSettings -Area $areaName -Object $label -SourceObject $connector -TargetObject $counterpart -SetCmdlet 'Set-ReceiveConnector' `
            -Exclude @('TransportRole', 'Usage') -BindingProperties @('Bindings') | Out-Null
        $status = if ([string]$connector.TransportRole -eq [string]$counterpart.TransportRole) { 'Equal' } else { 'Different' }
        Add-Result -Area $areaName -Object $label -Property 'TransportRole' -SourceValue $connector.TransportRole -TargetValue $counterpart.TransportRole -Status $status

        try {
            $sourceAces = @{}
            foreach ($ace in @(Get-ADPermission -Identity ([string]$connector.DistinguishedName) -ErrorAction Stop | Where-Object { -not [bool]$_.IsInherited })) { $sourceAces[(Get-AceKey -Ace $ace)] = Get-AceDescription -Ace $ace }
            $targetAces = @{}
            foreach ($ace in @(Get-ADPermission -Identity ([string]$counterpart.DistinguishedName) -ErrorAction Stop | Where-Object { -not [bool]$_.IsInherited })) { $targetAces[(Get-AceKey -Ace $ace)] = Get-AceDescription -Ace $ace }
            foreach ($key in $sourceAces.Keys) {
                $status = if ($targetAces.ContainsKey($key)) { 'Equal' } else { 'SourceOnly' }
                Add-Result -Area $areaName -Object $label -Property 'ADPermission' -SourceValue $sourceAces[$key] -TargetValue $(if ($status -eq 'Equal') { $sourceAces[$key] } else { '' }) -Status $status
            }
            foreach ($key in $targetAces.Keys) {
                if ($sourceAces.ContainsKey($key)) { continue }
                Add-Result -Area $areaName -Object $label -Property 'ADPermission' -TargetValue $targetAces[$key] -Status TargetOnly
            }
        }
        catch { Add-Result -Area $areaName -Object $label -Property 'ADPermission' -Status Info -Message ('Permissions not readable: {0}' -f $_.Exception.Message) }
    }
    foreach ($connector in $targetConnectors) {
        $found = $false
        foreach ($sourceConnector in $sourceConnectors) { if ((Convert-ServerName -Value ([string]$sourceConnector.Name)) -eq [string]$connector.Name) { $found = $true; break } }
        if (-not $found) { Add-Result -Area $areaName -Object ([string]$connector.Name) -Property '(exists)' -TargetValue 'present' -Status TargetOnly -Message 'Connector exists on the target only.' }
    }
}

function Invoke-AreaSendConnectors {
    foreach ($connector in @(Get-SendConnector -ErrorAction Stop)) {
        $servers = Get-ValueList -Value (ConvertTo-SettableValue -Value $connector.SourceTransportServers)
        $onSource = $servers -contains $script:SourceShort
        $onTarget = $servers -contains $script:TargetShort
        if (-not $onSource -and -not $onTarget) { continue }
        $status = if ($onSource -and $onTarget) { 'Equal' } elseif ($onSource) { 'SourceOnly' } else { 'TargetOnly' }
        Add-Result -Area 'SendConnectors' -Object ([string]$connector.Name) -Property 'SourceTransportServers' -SourceValue $(if ($onSource) { 'member' } else { '' }) -TargetValue $(if ($onTarget) { 'member' } else { '' }) -Status $status -Message ($servers -join ', ')
    }
}

function Invoke-AreaTransportAgents {
    $areaName = 'TransportAgents'
    foreach ($transportService in @('Hub', 'FrontEnd')) {
        $sourceAgents = @(Get-TransportAgent -Server $script:SourceShort -TransportService $transportService -ErrorAction Stop)
        $targetAgents = @(Get-TransportAgent -Server $script:TargetShort -TransportService $transportService -ErrorAction Stop)
        foreach ($agent in $sourceAgents) {
            $name = [string]$agent.Identity
            if (-not $name) { continue }
            $label = '{0}\{1}' -f $transportService, $name
            $counterpart = $targetAgents | Where-Object { [string]$_.Identity -eq $name } | Select-Object -First 1
            if ($null -eq $counterpart) { Add-Result -Area $areaName -Object $label -Property '(exists)' -SourceValue ('enabled {0}, priority {1}' -f $agent.Enabled, $agent.Priority) -Status SourceOnly; continue }
            $status = if ([bool]$agent.Enabled -eq [bool]$counterpart.Enabled) { 'Equal' } else { 'Different' }
            Add-Result -Area $areaName -Object $label -Property 'Enabled' -SourceValue $agent.Enabled -TargetValue $counterpart.Enabled -Status $status
            $status = if ([string]$agent.Priority -eq [string]$counterpart.Priority) { 'Equal' } else { 'Different' }
            Add-Result -Area $areaName -Object $label -Property 'Priority' -SourceValue $agent.Priority -TargetValue $counterpart.Priority -Status $status
        }
        foreach ($agent in $targetAgents) {
            if (-not [string]$agent.Identity) { continue }
            if ($sourceAgents | Where-Object { [string]$_.Identity -eq [string]$agent.Identity }) { continue }
            Add-Result -Area $areaName -Object ('{0}\{1}' -f $transportService, $agent.Identity) -Property '(exists)' -TargetValue ('enabled {0}, priority {1}' -f $agent.Enabled, $agent.Priority) -Status TargetOnly
        }
    }
}

function Invoke-AreaHybrid {
    $hybrid = $null
    try { $hybrid = Get-HybridConfiguration -ErrorAction Stop } catch { }
    if ($null -eq $hybrid) { Add-Result -Area 'Hybrid' -Object 'HybridConfiguration' -Property '(exists)' -Status Info -Message 'No hybrid configuration.'; return }
    foreach ($property in @('SendingTransportServers', 'ReceivingTransportServers', 'EdgeTransportServers')) {
        $servers = Get-ValueList -Value (ConvertTo-SettableValue -Value $hybrid.$property)
        $onSource = $servers -contains $script:SourceShort
        $onTarget = $servers -contains $script:TargetShort
        if (-not $onSource -and -not $onTarget) { continue }
        $status = if ($onSource -and $onTarget) { 'Equal' } elseif ($onSource) { 'SourceOnly' } else { 'TargetOnly' }
        Add-Result -Area 'Hybrid' -Object 'HybridConfiguration' -Property $property -SourceValue $(if ($onSource) { 'member' } else { '' }) -TargetValue $(if ($onTarget) { 'member' } else { '' }) -Status $status -Message ($servers -join ', ')
    }
}

function Get-ExchangeInstallShare {
    param($ExchangeServer)
    $dataPath = [string]$ExchangeServer.DataPath
    $installPath = 'C:\Program Files\Microsoft\Exchange Server\V15'
    if ($dataPath) { $installPath = Split-Path -Path $dataPath -Parent }
    return ('\\{0}\{1}' -f $ExchangeServer.Fqdn, ($installPath -replace '^([A-Za-z]):', '$1$$'))
}

function Invoke-AreaConfigFiles {
    $areaName = 'ConfigFiles'
    $sourceRoot = Get-ExchangeInstallShare -ExchangeServer $script:SourceExchangeServer
    $targetRoot = Get-ExchangeInstallShare -ExchangeServer $script:TargetExchangeServer
    if (-not (Test-Path $sourceRoot) -or -not (Test-Path $targetRoot)) {
        Add-Result -Area $areaName -Object 'admin share' -Property '(access)' -SourceValue $sourceRoot -TargetValue $targetRoot -Status Info -Message 'Admin share not reachable, config files not compared.'
        return
    }
    $files = @(
        'Bin\EdgeTransport.exe.config', 'Bin\MSExchangeFrontendTransport.exe.config', 'Bin\MSExchangeDelivery.exe.config',
        'Bin\MSExchangeSubmission.exe.config', 'Bin\MSExchangeMailboxReplication.exe.config', 'Bin\Microsoft.Exchange.Store.Worker.exe.config',
        'Bin\Microsoft.Exchange.Imap4.exe.config', 'Bin\Microsoft.Exchange.Imap4Service.exe.config', 'Bin\Microsoft.Exchange.Pop3.exe.config',
        'Bin\Microsoft.Exchange.Pop3Service.exe.config', 'Bin\Microsoft.Exchange.Directory.TopologyService.exe.config', 'Bin\Microsoft.Exchange.ServiceHost.exe.config',
        'TransportRoles\Shared\agents.config', 'TransportRoles\Shared\fetagents.config',
        'FrontEnd\HttpProxy\SharedWebConfig.config', 'FrontEnd\HttpProxy\web.config', 'FrontEnd\HttpProxy\owa\web.config', 'FrontEnd\HttpProxy\owa\auth\logon.aspx',
        'FrontEnd\HttpProxy\ecp\web.config', 'FrontEnd\HttpProxy\ews\web.config', 'FrontEnd\HttpProxy\rpc\web.config', 'FrontEnd\HttpProxy\mapi\web.config',
        'FrontEnd\HttpProxy\sync\web.config', 'FrontEnd\HttpProxy\oab\web.config', 'FrontEnd\HttpProxy\Autodiscover\web.config', 'FrontEnd\HttpProxy\PowerShell\web.config',
        'ClientAccess\SharedWebConfig.config', 'ClientAccess\Owa\web.config', 'ClientAccess\ecp\web.config', 'ClientAccess\exchweb\ews\web.config',
        'ClientAccess\Sync\web.config', 'ClientAccess\Autodiscover\web.config', 'ClientAccess\mapi\emsmdb\web.config', 'ClientAccess\mapi\nspi\web.config',
        'ClientAccess\PowerShell\web.config', 'ClientAccess\rpc\web.config', 'ClientAccess\OAB\web.config'
    )
    foreach ($relativePath in $files) {
        $sourcePath = Join-Path $sourceRoot $relativePath
        $targetPath = Join-Path $targetRoot $relativePath
        $sourceExists = Test-Path $sourcePath
        $targetExists = Test-Path $targetPath
        if (-not $sourceExists -and -not $targetExists) { continue }
        if (-not $targetExists) { Add-Result -Area $areaName -Object $relativePath -Property 'File' -SourceValue 'present' -Status SourceOnly; continue }
        if (-not $sourceExists) { Add-Result -Area $areaName -Object $relativePath -Property 'File' -TargetValue 'present' -Status TargetOnly; continue }
        $sourceHash = (Get-FileHash -Path $sourcePath -Algorithm SHA256).Hash
        $targetHash = (Get-FileHash -Path $targetPath -Algorithm SHA256).Hash
        $status = if ($sourceHash -eq $targetHash) { 'Equal' } else { 'Different' }
        Add-Result -Area $areaName -Object $relativePath -Property 'SHA256' -SourceValue $sourceHash.Substring(0, 16) -TargetValue $targetHash.Substring(0, 16) -Status $status `
            -Message $(if ($status -eq 'Different') { 'Compare both files, a customisation is likely.' } else { '' })
    }

    # OWA logon customisations and custom themes.
    $authFolder = 'FrontEnd\HttpProxy\owa\auth'
    $sourceAuth = Join-Path $sourceRoot $authFolder
    $targetAuth = Join-Path $targetRoot $authFolder
    if ((Test-Path $sourceAuth) -and (Test-Path $targetAuth)) {
        $targetFiles = @{}
        foreach ($file in @(Get-ChildItem -Path $targetAuth -Recurse -File -ErrorAction SilentlyContinue)) { $targetFiles[$file.FullName.Substring($targetAuth.Length).TrimStart('\')] = $file }
        foreach ($file in @(Get-ChildItem -Path $sourceAuth -Recurse -File -ErrorAction SilentlyContinue)) {
            $relative = $file.FullName.Substring($sourceAuth.Length).TrimStart('\')
            $counterpart = $targetFiles[$relative]
            if ($null -eq $counterpart) { Add-Result -Area $areaName -Object (Join-Path $authFolder $relative) -Property 'File' -SourceValue $file.Length -Status SourceOnly -Message 'OWA logon customisation.'; continue }
            if ($counterpart.Length -ne $file.Length -or ($file.Length -lt 5MB -and (Get-FileHash -Path $file.FullName -Algorithm SHA256).Hash -ne (Get-FileHash -Path $counterpart.FullName -Algorithm SHA256).Hash)) {
                Add-Result -Area $areaName -Object (Join-Path $authFolder $relative) -Property 'File' -SourceValue $file.Length -TargetValue $counterpart.Length -Status Different -Message 'OWA logon customisation.'
            }
        }
    }
    $sourcePrem = Join-Path $sourceRoot 'ClientAccess\Owa\prem'
    $targetPrem = Join-Path $targetRoot 'ClientAccess\Owa\prem'
    if ((Test-Path $sourcePrem) -and (Test-Path $targetPrem)) {
        $sourceThemes = @(Get-ChildItem -Path (Join-Path $sourcePrem '*\resources\themes') -Directory -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name | Sort-Object -Unique)
        $targetThemes = @(Get-ChildItem -Path (Join-Path $targetPrem '*\resources\themes') -Directory -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name | Sort-Object -Unique)
        foreach ($theme in $sourceThemes) { if ($targetThemes -notcontains $theme) { Add-Result -Area $areaName -Object ('owa theme {0}' -f $theme) -Property 'Folder' -SourceValue 'present' -Status SourceOnly } }
        foreach ($theme in $targetThemes) { if ($sourceThemes -notcontains $theme) { Add-Result -Area $areaName -Object ('owa theme {0}' -f $theme) -Property 'Folder' -TargetValue 'present' -Status TargetOnly } }
    }
}

$script:IisReadScript = {
    Import-Module WebAdministration -ErrorAction Stop
    $site = 'IIS:\Sites\Default Web Site'
    $redirect = Get-WebConfiguration -Filter 'system.webServer/httpRedirect' -PSPath $site
    $sslRaw = Get-WebConfigurationProperty -Filter 'system.webServer/security/access' -Name sslFlags -PSPath $site
    $sslValue = $sslRaw
    if ($null -ne $sslRaw -and $null -ne $sslRaw.PSObject.Properties['Value']) { $sslValue = $sslRaw.Value }
    [pscustomobject]@{
        RedirectEnabled          = [bool]$redirect.enabled
        RedirectDestination      = [string]$redirect.destination
        RedirectExactDestination = [bool]$redirect.exactDestination
        RedirectChildOnly        = [bool]$redirect.childOnly
        RedirectStatus           = [string]$redirect.httpResponseStatus
        SslFlags                 = [string]$sslValue
        Bindings                 = @(Get-WebBinding -Name 'Default Web Site' | ForEach-Object { '{0} {1}' -f $_.protocol, $_.bindingInformation })
    }
}

function Invoke-AreaIis {
    $areaName = 'Iis'
    try {
        $sourceIis = Invoke-Command -ComputerName $script:SourceFqdn -ScriptBlock $script:IisReadScript -ErrorAction Stop
        $targetIis = Invoke-Command -ComputerName $script:TargetFqdn -ScriptBlock $script:IisReadScript -ErrorAction Stop
    }
    catch { Add-Result -Area $areaName -Object 'Default Web Site' -Property '(read)' -Status Info -Message ('WinRM read failed: {0}' -f $_.Exception.Message); return }
    foreach ($property in @('RedirectEnabled', 'RedirectDestination', 'RedirectExactDestination', 'RedirectChildOnly', 'RedirectStatus', 'SslFlags')) {
        $status = if ([string]$sourceIis.$property -eq [string]$targetIis.$property) { 'Equal' } else { 'Different' }
        Add-Result -Area $areaName -Object 'Default Web Site' -Property $property -SourceValue $sourceIis.$property -TargetValue $targetIis.$property -Status $status
    }
    $sourceBindings = @($sourceIis.Bindings | Sort-Object)
    $targetBindings = @($targetIis.Bindings | Sort-Object)
    $status = if ((Get-CompareKey $sourceBindings) -eq (Get-CompareKey $targetBindings)) { 'Equal' } else { 'Different' }
    Add-Result -Area $areaName -Object 'Default Web Site' -Property 'Bindings' -SourceValue $sourceBindings -TargetValue $targetBindings -Status $status
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if (-not (Get-Command -Name Get-ExchangeServer -ErrorAction SilentlyContinue)) {
    throw 'Exchange cmdlets are not available. Run this script from the Exchange Management Shell or import a remote Exchange session first.'
}

$script:SourceExchangeServer = Get-ExchangeServer -Identity $SourceServer -ErrorAction Stop
$script:TargetExchangeServer = Get-ExchangeServer -Identity $TargetServer -ErrorAction Stop
$script:SourceShort = [string]$script:SourceExchangeServer.Name
$script:TargetShort = [string]$script:TargetExchangeServer.Name
$script:SourceFqdn  = [string]$script:SourceExchangeServer.Fqdn
$script:TargetFqdn  = [string]$script:TargetExchangeServer.Fqdn
if ($script:SourceShort -eq $script:TargetShort) { throw 'Source and target are the same server.' }

if (-not $OutputPath) {
    $OutputPath = Join-Path (Get-Location).Path ('ExchangeServerConfigCompare_{0}_vs_{1}_{2}' -f $script:SourceShort, $script:TargetShort, (Get-Date -Format 'yyyyMMdd_HHmmss'))
}
if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }
$outputFolder = (Resolve-Path $OutputPath).Path

Write-Host ('Comparing {0} (source) with {1} (target)' -f $script:SourceFqdn, $script:TargetFqdn) -ForegroundColor Cyan

$areaFunctions = @{
    Certificates = 'Invoke-AreaCertificates'; ExchangeServer = 'Invoke-AreaExchangeServer'; ClientAccess = 'Invoke-AreaClientAccess'
    VirtualDirectories = 'Invoke-AreaVirtualDirectories'; OutlookAnywhere = 'Invoke-AreaOutlookAnywhere'; Transport = 'Invoke-AreaTransport'
    PopImap = 'Invoke-AreaPopImap'; MailboxServer = 'Invoke-AreaMailboxServer'; Malware = 'Invoke-AreaMalware'; EventLogLevels = 'Invoke-AreaEventLogLevels'
    SettingOverrides = 'Invoke-AreaSettingOverrides'; ReceiveConnectors = 'Invoke-AreaReceiveConnectors'; SendConnectors = 'Invoke-AreaSendConnectors'
    TransportAgents = 'Invoke-AreaTransportAgents'; ConfigFiles = 'Invoke-AreaConfigFiles'; Iis = 'Invoke-AreaIis'; Hybrid = 'Invoke-AreaHybrid'
}

foreach ($areaName in $script:AllAreas) {
    if ($Area -and $Area -notcontains $areaName) { continue }
    if ($SkipArea -contains $areaName) { continue }
    Write-AreaHeader -Title $areaName
    $before = $script:Results.Count
    try { & $areaFunctions[$areaName] }
    catch {
        Write-Host ('  ERROR: {0}' -f $_.Exception.Message) -ForegroundColor Red
        Add-Result -Area $areaName -Object $script:TargetShort -Property '(area)' -Status Info -Message ('Area failed: {0}' -f $_.Exception.Message)
    }
    $areaRows = @($script:Results | Select-Object -Skip $before)
    $areaDifferences = @($areaRows | Where-Object { $_.Status -in @('Different', 'SourceOnly', 'TargetOnly') })
    if ($areaDifferences.Count -eq 0) { Write-Host '  in sync' -ForegroundColor Green }
    else {
        foreach ($row in $areaDifferences) {
            Write-Host ('  {0,-10} {1} | {2} | source: {3} | target: {4}' -f $row.Status, $row.Object, $row.Property, $row.Source, $row.Target) -ForegroundColor Yellow
        }
    }
}

# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------

$csvPath = Join-Path $outputFolder 'compare.csv'
$htmlPath = Join-Path $outputFolder 'compare.html'
$script:Results | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8

$style = @'
<style>
body { font-family: Segoe UI, Arial, sans-serif; font-size: 13px; margin: 24px; }
h1 { font-size: 20px; } h2 { font-size: 15px; margin-top: 28px; }
table { border-collapse: collapse; width: 100%; }
th { background: #1B2B4B; color: #fff; text-align: left; padding: 6px 8px; }
td { border-bottom: 1px solid #ddd; padding: 5px 8px; vertical-align: top; word-break: break-word; }
tr.Different td { background: #fff3cd; } tr.SourceOnly td { background: #f8d7da; } tr.TargetOnly td { background: #d1ecf1; }
tr.Equal td { color: #555; } tr.Info td { color: #777; font-style: italic; }
.summary td { padding: 4px 12px 4px 0; border: none; }
</style>
'@
$encode = { param($Text) [System.Net.WebUtility]::HtmlEncode([string]$Text) }
$html = New-Object System.Text.StringBuilder
[void]$html.AppendLine('<!DOCTYPE html><html><head><meta charset="utf-8"><title>Exchange server configuration compare</title>' + $style + '</head><body>')
[void]$html.AppendLine(('<h1>Exchange server configuration compare</h1><p>Source <b>{0}</b>, target <b>{1}</b>, {2}</p>' -f (& $encode $script:SourceFqdn), (& $encode $script:TargetFqdn), (Get-Date -Format 'yyyy-MM-dd HH:mm')))
[void]$html.AppendLine('<table class="summary"><tr><th>Area</th><th>Different</th><th>SourceOnly</th><th>TargetOnly</th><th>Equal</th></tr>')
foreach ($group in ($script:Results | Group-Object -Property Area)) {
    [void]$html.AppendLine(('<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td></tr>' -f $group.Name,
        @($group.Group | Where-Object Status -eq 'Different').Count, @($group.Group | Where-Object Status -eq 'SourceOnly').Count,
        @($group.Group | Where-Object Status -eq 'TargetOnly').Count, @($group.Group | Where-Object Status -eq 'Equal').Count))
}
[void]$html.AppendLine('</table>')
foreach ($group in ($script:Results | Group-Object -Property Area)) {
    [void]$html.AppendLine(('<h2>{0}</h2><table><tr><th>Status</th><th>Object</th><th>Property</th><th>{1}</th><th>{2}</th><th>Message</th></tr>' -f $group.Name, (& $encode $script:SourceShort), (& $encode $script:TargetShort)))
    foreach ($row in $group.Group) {
        [void]$html.AppendLine(('<tr class="{0}"><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td><td>{5}</td></tr>' -f $row.Status,
            (& $encode $row.Object), (& $encode $row.Property), (& $encode $row.Source), (& $encode $row.Target), (& $encode $row.Message)))
    }
    [void]$html.AppendLine('</table>')
}
[void]$html.AppendLine('</body></html>')
$html.ToString() | Set-Content -Path $htmlPath -Encoding UTF8

$differences = @($script:Results | Where-Object { $_.Status -in @('Different', 'SourceOnly', 'TargetOnly') })
Write-Host ''
Write-Host '=== Summary ===' -ForegroundColor Cyan
$summary = foreach ($group in ($script:Results | Group-Object -Property Area)) {
    [pscustomobject]@{
        Area       = $group.Name
        Different  = @($group.Group | Where-Object Status -eq 'Different').Count
        SourceOnly = @($group.Group | Where-Object Status -eq 'SourceOnly').Count
        TargetOnly = @($group.Group | Where-Object Status -eq 'TargetOnly').Count
        Equal      = @($group.Group | Where-Object Status -eq 'Equal').Count
    }
}
if ($summary) { $summary | Format-Table -AutoSize | Out-String | Write-Host }
if ($differences.Count -eq 0) { Write-Host 'No differences found.' -ForegroundColor Green }
else { Write-Host ('{0} difference(s) found.' -f $differences.Count) -ForegroundColor Yellow }
Write-Host ('CSV : {0}' -f $csvPath)
Write-Host ('HTML: {0}' -f $htmlPath)

if ($PassThru) { $script:Results }
exit $differences.Count
